# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11995dc169b200f1b613645eafca6408cbb543f7d3bcfa260ab9e9c4565789c4a971c5f5b0a3f58964fad9dc20ac9d7ca82acb6f013f016c4e0cf9a37e02f2a2

test:
  secret_key_base: 53d9386022e4bfc75ce19f091e16ff23fbd8c62339ff5de2fd55d1ec01c0237d4f50b723c0283f7a5106232508050c0ec75eb117c6f50cfae7064211ce1cd48d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
